### ISSUE TITLE
Compile for ARM

### ISSUE THREAD

**Issue by GL513** [noahtheprogrammer/raptoreum-saltyminer#1]
Hi. Self explanitory. I would rather not do it myself as it's a pain to manually compile stuff most of the time.
also i claimed the first issue ha

**Comment by authrequest** [comment]
This would not work on ARM as it run the exe files. Plus ARM would give you like no hashrate at all unfortunately.

**Comment by noahtheprogrammer** [comment]
I have figured out how to compile for ARM and will publish it in the next release.
